### PR TITLE
added prettier-java 0.8.3 binary

### PR DESCRIPTION
**Pull request by sanjayrawat1**
Update the prettier-java version to 0.8.3 by adding binaries.
This update includes https://github.com/jhipster/prettier-java/pull/398

### CODE REVIEW

**Comment by sanjayrawat1** [comment]
Hi @jhaber, can you please merge this PR? Actually, I didn't find any doc about how to contribute, if anything needs to be added please let me know.

**Comment by jhaber** [comment]
sorry for the delay

**Comment by sanjayrawat1** [comment]
@jhaber can you make a release, please. I need the updated version of prettier-java in my new project.

**Comment by jhaber** [comment]
I just released version 0.11 which should show up in Maven central soon

**Pull request merged**
