### PR TITLE
Add eol conversion

### PR DESCRIPTION
**Pull request by MSaguer**
I had a new option endOfLine to enable the EOL conversion.
Usefull when users uses many different OS on the same project

### CODE REVIEW

**Comment by jhaber** [comment]
Thanks for the PR! The endOfLine changes look good to me. Looking at the binPath related changes, I think it would break for people on Linux/OSX because `/bin/diff` doesn't exist normally (at least as far as I can tell). What do you think about just changing `/bin/sh` to `sh` and requiring that both `sh` and `diff` are on the path (which they should be already for Linux/OSX users).

**Comment by MSaguer** [comment]
I don't know how I totally mixed my commits. binPath was a test I performed on the windows compliance. It should be removed from here.
I remove it immediately

**Comment by MSaguer** [comment]
Your comment about diff and sh path is already taken into account in the other pull request #12

**Comment by jhaber** [comment]
thanks for the contribution 👍

**Pull request merged**
