### PR TITLE
feat add glob parameter, fix #21

### LINKED ISSUE #21: Can i format single file from the command line?
[prettier-java](https://github.com/jhipster/prettier-java) has the ability to format the single file

image

Can i use this plugin to format the single file via the command line?

My real needs is to register a git hook like this [# option-6-shell-script](https://prettier.io/docs/en/precommit.html#option-6-shell-script)

### PR DESCRIPTION
**Pull request by GoldSubmarine**

### CODE REVIEW

**Comment by GoldSubmarine** [comment]
I've already tested it,it works well

**Comment by GoldSubmarine** [comment]
Is there any response?

**Comment by GoldSubmarine** [comment]
If anything needs to be modified please let me know.I'm not sure if you agree with the design 😃

**Comment by jhaber** [comment]
Sorry for the delay, I can review this PR shortly. My main question is how the glob parameter should interact with our regular source directory discovery (should it replace the discovered directories? union the results? filter the directories to files that match this glob?)

**Comment by GoldSubmarine** [comment]
In my opinion, if the user customizes, all of prettier functions should be provided, not only format java files, but also format markdown or javascript. What files need to be formatted is totally up to him, so we don't have to do anything for the result.

I just test by the absolute path, relative paths are now invalid.

**Comment by GoldSubmarine** [comment]
Maybe we can modify the startup path of nodejs to the current project root

**Comment by GoldSubmarine** [comment]
I've already tested it, relative paths also take effect.

**Comment by GoldSubmarine** [comment]
Perhaps by default, we should format all Java files, so we should remove the following code. Relate to #34 

https://github.com/HubSpot/prettier-maven-plugin/blob/41af5f47a4c3a72a373cb7fdc4105d1562bdc82a/src/main/java/com/hubspot/maven/plugins/prettier/AbstractPrettierMojo.java#L148-L149

If users only need to format certain folders, they should customize by glob config. Relate to #22

**Comment by 9inpachi** [comment]
I need this too. Would be great if the PR is merged. :)

**Comment by mnisius** [comment]
Yes it would be awsome if this plugin could format all of my project. Please merge.

**Comment by jhaber** [comment]
Sorry again for the delay, I went a slightly different direction in #39 with support for multiple patterns, rather than needing to stuff everything into a single glob

**Pull request closed without merging**
